// @appbuilder-oauth-v4
// AUTO-GENERATED by setup_oauth. Edit with care -- the LLM may regenerate.

import { createContext, useCallback, useEffect, useState, type ReactNode } from "react";
import { signInWithPopup } from "./auth-popup";

export type AuthUser = {
  id: string;
  email: string | null;
  name: string | null;
  picture: string | null;
  provider: string;
};

export type AuthContextValue = {
  user: AuthUser | null;
  status: "loading" | "authenticated" | "anonymous" | "error";
  signIn: (providerId: string, scopes?: string) => Promise<void>;
  signOut: () => Promise<void>;
  refresh: () => Promise<void>;
};

export const AuthContext = createContext<AuthContextValue | null>(null);

export function AuthProvider({ children }: { children: ReactNode }) {
  const [user, setUser] = useState<AuthUser | null>(null);
  const [status, setStatus] = useState<AuthContextValue["status"]>("loading");

  const refresh = useCallback(async () => {
    try {
      const resp = await fetch("/api/auth/me", { credentials: "include" });
      if (!resp.ok) {
        setUser(null);
        setStatus("anonymous");
        return;
      }
      const json = (await resp.json()) as { user: AuthUser | null };
      setUser(json.user);
      setStatus(json.user ? "authenticated" : "anonymous");
    } catch {
      setUser(null);
      setStatus("error");
    }
  }, []);

  const signIn = useCallback(async (providerId: string, scopes?: string) => {
    await signInWithPopup(providerId, scopes);
    await refresh();
  }, [refresh]);

  const signOut = useCallback(async () => {
    await fetch("/api/auth/logout", { method: "POST", credentials: "include" });
    setUser(null);
    setStatus("anonymous");
  }, []);

  useEffect(() => {
    refresh();
  }, [refresh]);

  return <AuthContext.Provider value={{ user, status, signIn, signOut, refresh }}>{children}</AuthContext.Provider>;
}
