// @appbuilder-oauth-v4
// AUTO-GENERATED by setup_oauth. Edit with care -- the LLM may regenerate.

/**
 * Open an OAuth popup that navigates directly to
 * `/api/auth/<providerId>/start` at the top level of the user's
 * browser, then resolve when the popup posts back a success message
 * (or reject on error / close).
 *
 * Why navigate directly to /start instead of pre-flighting from the
 * iframe and opening the popup at the provider URL:
 *
 *   1. **X-Frame-Options on the consent screen.** Many providers
 *      (Google) refuse to render their consent screen inside any
 *      iframe via `X-Frame-Options: DENY`. The popup escapes the
 *      sandbox iframe via `allow-popups-to-escape-sandbox` and runs
 *      at the top level, so the consent screen renders.
 *
 *   2. **Storage partitioning (CHIPS).** Chrome partitions cookies
 *      by the top-level frame. A `fetch("/api/auth/.../start")`
 *      from the AppBuilder iframe writes `oauth_state_*` /
 *      `oauth_verifier_*` cookies under
 *      `(top=AppBuilder, embedded=sandbox-host)`, but the popup's
 *      callback runs at top-level under `(top=sandbox-host)` and
 *      reads a different partition -- the cookies are missing and
 *      every flow fails with "OAuth state did not match". By
 *      letting the popup itself initiate `/start`, both the
 *      cookie write and the callback read happen in the same
 *      first-party partition.
 *
 * Caveat: after the popup posts back success, the iframe's
 * `fetch("/api/auth/me")` is still a third-party request relative
 * to the AppBuilder top frame. In browsers that fully block
 * third-party cookies, the session cookie set in the popup's
 * first-party jar will not be sent on that fetch and the user will
 * appear unauthenticated inside the preview. The deployed app on
 * Vercel runs as its own top-level frame with no iframe, so this
 * limitation is dev-preview-only.
 */
export async function signInWithPopup(providerId: string, scopes?: string): Promise<void> {
  const startUrl = scopes && scopes.length > 0
    ? `/api/auth/${providerId}/start?scopes=${encodeURIComponent(scopes)}`
    : `/api/auth/${providerId}/start`;

  const popup = window.open(startUrl, "appbuilder-oauth", "width=520,height=640");
  if (!popup) {
    // Popup-blocker fallback: when window.open returns null we
    // can't run the postMessage handshake at all -- there's no
    // child window to message back. Rather than tell the user
    // "Allow popups for this site and try again" and bounce off
    // every default-blocked browser, swap to a redirect flow:
    // navigate the CURRENT top-level page to /start with a
    // `returnTo` query param that captures where to drop the
    // user once OAuth completes. The callback handler reads that
    // returnTo (persisted by start.ts as a one-shot cookie
    // alongside state/verifier) and 302s back to it instead of
    // rendering the postMessage HTML.
    //
    // The user-gesture rules around window.open are notoriously
    // browser-specific and a trap for end users (Safari/Firefox
    // are stricter than Chrome; some browsers block ALL popups
    // for new sites by default). Falling back to a redirect on
    // null keeps "click button -> sign in" working everywhere
    // without a per-browser settings tour, at the cost of the
    // page being briefly replaced. The deployed (no iframe) case
    // is the only place this matters because browsers can't
    // legitimately block a top-level navigation triggered by a
    // user click.
    //
    // returnTo is always a SAME-ORIGIN absolute path (e.g.
    // "/dashboard", "/?welcome=1"). We deliberately strip any
    // scheme/host the caller might have synthesised; start.ts
    // re-validates server-side as defence in depth, but doing it
    // here too keeps the URL bar clean and makes the contract
    // visible at the call site.
    const here = typeof window !== "undefined" ? window.location : null;
    const safeReturn = here ? `${here.pathname}${here.search}${here.hash}` : "/";
    const sep = startUrl.includes("?") ? "&" : "?";
    window.location.href = `${startUrl}${sep}returnTo=${encodeURIComponent(safeReturn)}`;
    // Promise will never resolve here -- the page is navigating
    // away. Returning a never-resolving promise is intentional:
    // the caller (typically AuthProvider.signIn) is awaiting us
    // and would otherwise race a refresh() against the in-flight
    // navigation, briefly clearing the auth UI to "anonymous"
    // before the page actually unloads.
    return new Promise<void>(() => {});
  }

  // Capture the popup's expected origin once at open time. The
  // popup is opened via a relative URL, so its origin is always
  // the current window's origin -- we read it here (rather than
  // recomputing inside the listener) so a future
  // `window.history` mutation can't sneak the listener into
  // accepting a now-different origin. Anything that isn't this
  // exact origin is dropped on the floor before we read
  // `event.data`.
  const expectedOrigin = typeof window !== "undefined" ? window.location.origin : null;

  return await new Promise<void>((resolve, reject) => {
    const onMessage = async (event: MessageEvent) => {
      // Hard origin + source gate. Without it, ANY frame on the
      // page (a malicious ad, a sandboxed iframe of another origin
      // that misuses postMessage to the top frame, an extension
      // injection) can synthesize a fake `appbuilder-oauth-success`
      // event. The server-side HMAC on the exchange token still
      // gates session minting, but a forged event would cause us
      // to fire a POST /api/auth/exchange with attacker-supplied
      // bytes (DoS / replay of a stale leaked token) and resolve
      // or reject the in-flight signInWithPopup promise based on
      // attacker input (UX confusion). The two-pronged check
      // (`event.source === popup` AND `event.origin === expectedOrigin`)
      // is the standard postMessage defensive pattern.
      if (event.source !== popup) return;
      if (expectedOrigin !== null && event.origin !== expectedOrigin) return;
      const data = event.data as {
        type?: string;
        provider?: string;
        code?: string;
        message?: string;
        exchangeToken?: string | null;
      } | null;
      if (!data || typeof data !== "object") return;
      if (data.type === "appbuilder-oauth-success" && data.provider === providerId) {
        // Best-effort exchange call: redeems a short-lived HMAC
        // token for a Partitioned session cookie scoped to whatever
        // top-level site this iframe is embedded under. Without
        // this, browsers with third-party cookie blocking enabled
        // (Chrome 2026+, Safari, Firefox) refuse to send the
        // session cookie set by the popup callback, and the iframe
        // sees an anonymous session forever. Failures here are
        // recoverable -- the deployed app's same-origin session
        // cookie still works, so we resolve regardless and let the
        // caller's /api/auth/me refresh do the final check.
        if (typeof data.exchangeToken === "string" && data.exchangeToken.length > 0) {
          try {
            await fetch("/api/auth/exchange", {
              method: "POST",
              headers: { "Content-Type": "application/json" },
              credentials: "include",
              body: JSON.stringify({ token: data.exchangeToken }),
            });
          } catch {
            // Network-level failure: ignore and let /api/auth/me
            // resolve the user state. The exchange is purely an
            // iframe-partitioning workaround; a same-origin app
            // (deployed Vercel) has a perfectly good session
            // cookie already.
          }
        }
        cleanup();
        resolve();
      } else if (data.type === "appbuilder-oauth-error") {
        cleanup();
        reject(new Error(data.message ?? data.code ?? "Sign-in failed"));
      }
    };
    const interval = window.setInterval(() => {
      if (popup.closed) {
        cleanup();
        // The popup may have already posted success; resolving here
        // is the optimistic path. The caller should refetch
        // /api/auth/me to confirm.
        resolve();
      }
    }, 500);
    function cleanup() {
      window.removeEventListener("message", onMessage);
      window.clearInterval(interval);
      try {
        popup?.close();
      } catch {}
    }
    window.addEventListener("message", onMessage);
  });
}
