// @appbuilder-oauth-v4
// AUTO-GENERATED by setup_oauth. Edit with care -- the LLM may regenerate.

import { useContext } from "react";
import { AuthContext, type AuthContextValue } from "./AuthProvider";

export function useAuth(): AuthContextValue {
  const ctx = useContext(AuthContext);
  if (!ctx) throw new Error("useAuth must be used inside <AuthProvider>");
  return ctx;
}
