-- Auto-generated by AppBuilder v2 schema migration engine.
-- Version: 1
-- Name:    4 changes
-- DO NOT EDIT. Changes to schema.ts drive new migrations; this file is a
-- read-only record of what the platform applied for version 1.

CREATE TABLE IF NOT EXISTS "bin_locations" (
  "id" INTEGER GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  "code" TEXT NOT NULL,
  "name" TEXT NOT NULL,
  "zone" TEXT NOT NULL DEFAULT '',
  "aisle" TEXT NOT NULL DEFAULT '',
  "shelf" TEXT NOT NULL DEFAULT '',
  "description" TEXT NOT NULL DEFAULT '',
  "asset_tag" TEXT NOT NULL DEFAULT '',
  "is_active" BOOLEAN NOT NULL DEFAULT true,
  "updated_at" TIMESTAMPTZ DEFAULT now(),
  "created_at" TIMESTAMPTZ DEFAULT now(),
  PRIMARY KEY ("id")
);

CREATE TABLE IF NOT EXISTS "consumables" (
  "id" INTEGER GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  "name" TEXT NOT NULL,
  "sku" TEXT NOT NULL,
  "description" TEXT NOT NULL DEFAULT '',
  "quantity" INTEGER NOT NULL DEFAULT 0,
  "min_level" INTEGER NOT NULL DEFAULT 0,
  "unit" TEXT NOT NULL DEFAULT 'ea',
  "category" TEXT NOT NULL DEFAULT 'General',
  "bin_location" TEXT NOT NULL DEFAULT '',
  "asset_tag" TEXT NOT NULL DEFAULT '',
  "notes" TEXT NOT NULL DEFAULT '',
  "is_active" BOOLEAN NOT NULL DEFAULT true,
  "updated_at" TIMESTAMPTZ DEFAULT now(),
  "created_at" TIMESTAMPTZ DEFAULT now(),
  PRIMARY KEY ("id")
);

CREATE TABLE IF NOT EXISTS "printer_settings" (
  "id" INTEGER GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  "name" TEXT NOT NULL,
  "host" TEXT NOT NULL,
  "port" INTEGER NOT NULL DEFAULT 9100,
  "protocol" TEXT NOT NULL DEFAULT 'zpl',
  "label_width_mm" REAL NOT NULL DEFAULT 50,
  "label_height_mm" REAL NOT NULL DEFAULT 25,
  "dpi" INTEGER NOT NULL DEFAULT 203,
  "is_default" BOOLEAN NOT NULL DEFAULT false,
  "notes" TEXT NOT NULL DEFAULT '',
  "created_at" TIMESTAMPTZ DEFAULT now(),
  PRIMARY KEY ("id")
);

CREATE TABLE IF NOT EXISTS "stock_transactions" (
  "id" INTEGER GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  "consumable_id" INTEGER NOT NULL,
  "change_amount" INTEGER NOT NULL,
  "previous_quantity" INTEGER NOT NULL,
  "new_quantity" INTEGER NOT NULL,
  "reason" TEXT NOT NULL DEFAULT 'adjust',
  "note" TEXT NOT NULL DEFAULT '',
  "created_by" TEXT NOT NULL DEFAULT 'operator',
  "created_at" TIMESTAMPTZ DEFAULT now(),
  PRIMARY KEY ("id")
);
