// @appbuilder-oauth-v4
// AUTO-GENERATED by setup_oauth. Edit with care -- the LLM may regenerate.

import type { IncomingMessage, ServerResponse } from "node:http";
// See start.ts: explicit `.js` is required for Node ESM on Vercel.
import { setSession, verifyExchangeToken } from "./_lib/session.js";

/**
 * Iframe-partitioned session handoff endpoint.
 *
 * Why this exists: in the AppBuilder dev preview the app runs inside
 * an iframe whose top frame is the AppBuilder host. Modern browsers
 * (Chrome 2026+, Safari, Firefox) partition cookies by top-level
 * site (CHIPS / total storage partitioning). The popup that
 * completes OAuth runs at the **top level** of the sandbox host, so
 * the session cookie set by `<provider>/callback` lands in the
 * sandbox host's first-party (or `top=sandbox-host` partitioned)
 * jar -- the iframe (`top=AppBuilder`) never sees it, and
 * `/api/auth/me` from inside the iframe always returns null.
 *
 * Fix: the popup callback mints a short-lived HMAC-signed exchange
 * token containing the session payload and posts it to the opener
 * via `window.postMessage`. The iframe redeems the token here
 * (POST /api/auth/exchange), and because this request is initiated
 * from inside the iframe, the Partitioned session cookie we emit is
 * stored under `(top=AppBuilder, embedded=sandbox-host)` -- the
 * same partition the iframe's subsequent `/api/auth/me` reads
 * from. Sign-in now persists across page loads inside the preview.
 *
 * In the deployed app (no iframe; top-level same as the API origin)
 * the exchange round-trip is harmless but redundant: `callback.ts`
 * already set a usable session cookie in the deployed site's
 * partition. The frontend treats the exchange as best-effort and
 * falls through to a normal `/api/auth/me` refresh on any failure.
 */
export default async function handler(req: IncomingMessage, res: ServerResponse) {
  if (req.method !== "POST") {
    res.statusCode = 405;
    res.setHeader("Allow", "POST");
    res.end("Method Not Allowed");
    return;
  }

  type ExchangeBody = { token?: unknown };
  const body = (typeof (req as IncomingMessage & { body?: unknown }).body === "object" && (req as IncomingMessage & { body?: unknown }).body !== null
    ? (req as IncomingMessage & { body?: ExchangeBody }).body
    : {}) as ExchangeBody;
  const token = typeof body.token === "string" ? body.token : "";
  if (!token) {
    res.statusCode = 400;
    res.setHeader("Content-Type", "application/json");
    res.end(JSON.stringify({ error: "missing_token" }));
    return;
  }

  const session = await verifyExchangeToken(token);
  if (!session) {
    // Either the HMAC didn't verify or the token expired (60s TTL).
    // We deliberately don't distinguish the two cases: telling an
    // attacker which knob to twiddle is a free leak with no
    // legitimate user benefit.
    res.statusCode = 401;
    res.setHeader("Content-Type", "application/json");
    res.end(JSON.stringify({ error: "invalid_token" }));
    return;
  }

  await setSession(res, session);
  res.statusCode = 200;
  res.setHeader("Content-Type", "application/json");
  res.end(JSON.stringify({
    ok: true,
    user: {
      id: session.sub,
      email: session.email ?? null,
      name: session.name ?? null,
      picture: session.picture ?? null,
      provider: session.provider,
    },
  }));
}
