// @appbuilder-oauth-v4
// AUTO-GENERATED by setup_oauth. Edit with care -- the LLM may regenerate.

import type { IncomingMessage, ServerResponse } from "node:http";
// See start.ts: explicit `.js` is required for Node ESM on Vercel.
import { clearSession } from "./_lib/session.js";
import { assertSameSiteRequest } from "./_lib/redirect-uri.js";

/**
 * Sign-out endpoint.
 *
 * `POST`-only by design (CSRF defence). The session cookie is set
 * with `SameSite=None; Partitioned` so it can flow into the
 * iframe-partitioned dev preview, which means browsers will happily
 * include it on cross-site GETs (`<img src=".../api/auth/logout">`,
 * top-level navigations, prefetches). Without an explicit method
 * allowlist any third-party page can force-sign-out an authenticated
 * user. Pinning to POST means the only way to trigger logout is a
 * fetch / form submission, which is gated by CORS + a same-origin
 * caller — exactly the threat model the SameSite cookie attribute
 * relies on. The matching frontend in `AuthProvider.tsx` already
 * uses `fetch(..., { method: "POST" })`.
 */
export default async function handler(req: IncomingMessage, res: ServerResponse) {
  if (req.method !== "POST") {
    res.statusCode = 405;
    res.setHeader("Allow", "POST");
    res.end("Method Not Allowed");
    return;
  }
  // Defense-in-depth: 405 alone doesn't stop a hostile cross-site
  // `<form method="POST">`. `SameSite=None;Partitioned` cookies
  // DO flow on those, so we also require an affirmative same-origin
  // signal (Sec-Fetch-Site, with an Origin-header fallback).
  if (!assertSameSiteRequest(req)) {
    res.statusCode = 403;
    res.end("Cross-site request blocked");
    return;
  }

  clearSession(res);
  res.statusCode = 200;
  res.setHeader("Content-Type", "application/json");
  res.end(JSON.stringify({ ok: true }));
}
