// @appbuilder-oauth-v4
// AUTO-GENERATED by setup_oauth. Edit with care -- the LLM may regenerate.

import type { IncomingMessage, ServerResponse } from "node:http";
// See start.ts: explicit `.js` is required for Node ESM on Vercel.
import { loadSession } from "./_lib/session.js";

export default async function handler(req: IncomingMessage, res: ServerResponse) {
  const session = await loadSession(req);
  res.statusCode = 200;
  res.setHeader("Content-Type", "application/json");
  if (!session) {
    res.end(JSON.stringify({ user: null }));
    return;
  }
  res.end(JSON.stringify({
    user: {
      id: session.sub,
      email: session.email ?? null,
      name: session.name ?? null,
      picture: session.picture ?? null,
      provider: session.provider,
    },
  }));
}
