// @appbuilder-oauth-v4
// AUTO-GENERATED by setup_oauth. Edit with care -- the LLM may regenerate.

import type { IncomingMessage, ServerResponse } from "node:http";
// See start.ts: explicit `.js` is required for Node ESM on Vercel.
import { loadSession, setSession } from "./_lib/session.js";
import { assertSameSiteRequest } from "./_lib/redirect-uri.js";

/**
 * Sliding-window session refresh: bumps `exp` so the user stays
 * signed in across long-running sessions without needing to re-prompt
 * the upstream provider. Refresh-token rotation against the upstream
 * provider is intentionally out of scope for v1 -- when the access
 * token expires the user signs in again.
 *
 * `POST`-only by design (CSRF defence). Same threat model as
 * `logout.ts`: the session cookie is `SameSite=None; Partitioned`
 * to satisfy the iframe-partitioning path, so browsers WILL include
 * it on cross-site GETs. A persistent attacker page that simply gets
 * loaded by the victim could otherwise re-issue a fresh
 * sliding-window cookie indefinitely (extending sessions forever
 * with zero user interaction). Restricting to POST forces the
 * caller to be a same-origin fetch / form submission. Any future
 * frontend that wires this up MUST send `{ method: "POST" }`; the
 * scaffolded `AuthProvider.tsx` doesn't auto-call refresh today.
 */
export default async function handler(req: IncomingMessage, res: ServerResponse) {
  if (req.method !== "POST") {
    res.statusCode = 405;
    res.setHeader("Allow", "POST");
    res.end("Method Not Allowed");
    return;
  }
  // Defense-in-depth (same rationale as `logout.ts`): a hostile
  // cross-site `<form method="POST">` includes the
  // `SameSite=None;Partitioned` session cookie, so 405 alone
  // doesn't stop someone from indefinitely renewing a victim's
  // sliding-window session in the background.
  if (!assertSameSiteRequest(req)) {
    res.statusCode = 403;
    res.end("Cross-site request blocked");
    return;
  }

  const session = await loadSession(req);
  if (!session) {
    res.statusCode = 401;
    res.setHeader("Content-Type", "application/json");
    res.end(JSON.stringify({ ok: false }));
    return;
  }
  const now = Math.floor(Date.now() / 1000);
  await setSession(res, { ...session, iat: now, exp: now + 60 * 60 * 24 * 7 });
  res.statusCode = 200;
  res.setHeader("Content-Type", "application/json");
  res.end(JSON.stringify({ ok: true }));
}
