// @appbuilder-oauth-v4
// AUTO-GENERATED by setup_oauth. Edit with care -- the LLM may regenerate.

export type SandboxOAuthProvider = {
  id: string;
  authorizeUrl: string;
  tokenUrl: string;
  userInfoUrl: string | null;
  defaultScopes: string;
  requestsRefreshToken: boolean;
  clientIdEnv: string;
  clientSecretEnv: string;
};

export const PROVIDERS: Record<string, SandboxOAuthProvider> = {
  google: {
    id: "google",
    authorizeUrl: "https://accounts.google.com/o/oauth2/v2/auth",
    tokenUrl: "https://oauth2.googleapis.com/token",
    userInfoUrl: "https://openidconnect.googleapis.com/v1/userinfo",
    defaultScopes: "openid email profile",
    requestsRefreshToken: true,
    clientIdEnv: "GOOGLE_CLIENT_ID",
    clientSecretEnv: "GOOGLE_CLIENT_SECRET",
  }
};

export function getProvider(id: string): SandboxOAuthProvider | null {
  return PROVIDERS[id] ?? null;
}
