// @appbuilder-oauth-v4
// AUTO-GENERATED by setup_oauth. Edit with care -- the LLM may regenerate.

import type { IncomingMessage } from "node:http";

/**
 * Compute the absolute redirect URI for the running environment.
 *
 * Why dynamic? The same code runs in three places:
 *   - Vite dev plugin in the AppBuilder sandbox iframe (origin =
 *     a tenant-specific *.csb.app / *.preview-iframe URL, varies per
 *     session).
 *   - Vercel preview deploys (origin = *.vercel.app, generated per push).
 *   - Vercel production (origin = the user's custom domain).
 *
 * Hardcoding any of these breaks the others, so we resolve the origin
 * from the incoming request. `X-Forwarded-Host` / `X-Forwarded-Proto`
 * win when present (Vercel and most reverse proxies set them); we fall
 * back to `Host` for direct connections.
 *
 * Important: the value returned here MUST exactly match one of the
 * "Authorized redirect URIs" entered into the provider's console
 * (Google Cloud Console, etc.), modulo trailing slash. The LLM
 * surfaces the exact value to the user via the OAuth setup panel so
 * they can paste it verbatim.
 */
export function getRedirectUri(req: IncomingMessage, providerId: string): string {
  // Fall back to `http://localhost` when no Host can be resolved.
  // `getOrigin` returns null in that case (the postMessage callers
  // explicitly handle null by widening to `"*"`), but the redirect
  // URI is sent verbatim to the OAuth provider -- interpolating
  // `null` would produce `"null/api/auth/.../callback"` and the
  // provider would reject it with `redirect_uri_mismatch`,
  // breaking the entire sign-in flow. The original implementation
  // had the same fallback baked in; keeping it here preserves
  // local-dev behaviour while letting `getOrigin` retain its
  // null-as-signal contract for the postMessage path.
  const origin = getOrigin(req) ?? "http://localhost";
  return `${origin}/api/auth/${providerId}/callback`;
}

/**
 * Resolve the popup's own origin (`<scheme>://<host>`) from the
 * incoming request. Used as a `postMessage` `targetOrigin` so the
 * callback handshake can't be addressed cross-origin: the popup is
 * always opened by a same-origin caller (`auth-popup.ts` invokes
 * `window.open("/api/auth/<provider>/start", ...)` with a relative
 * path), so the opener's origin equals the callback's origin.
 *
 * Returns `null` when no host can be resolved -- callers should
 * fall back to `"*"` (postMessage path) or `http://localhost`
 * (redirect-URI path) and rely on the HMAC-signed exchange token's
 * 60-second TTL to bound replay risk in the degraded postMessage
 * branch.
 *
 * Scheme resolution: a forwarded proto (`x-forwarded-proto`) wins
 * unconditionally so PaaS deployments behind TLS-terminating proxies
 * (Vercel, Render, Fly) get `https` even when the upstream Node
 * request is plain HTTP. Without a forwarded proto we infer
 * `http` for ALL loopback hosts (`localhost`, the `127.0.0.0/8`
 * IPv4 block, and the `[::1]` IPv6 literal) so a dev server bound
 * to `127.0.0.1:3000` doesn't get an `https://127.0.0.1:3000`
 * postMessage targetOrigin -- which would never match the popup's
 * actual `http://127.0.0.1:3000` origin and break sign-in.
 * Everything else falls through to `https`.
 */
export function getOrigin(req: IncomingMessage): string | null {
  const forwardedProto = readHeader(req, "x-forwarded-proto");
  const forwardedHost = readHeader(req, "x-forwarded-host");
  const host = forwardedHost ?? readHeader(req, "host");
  if (!host) return null;
  const proto = forwardedProto ?? (isLoopbackHost(host) ? "http" : "https");
  return `${proto}://${host}`;
}

/**
 * Strip the port (and IPv6 brackets) from a Host header and decide
 * whether the bare host is a loopback address. Used by getOrigin
 * to infer `http` vs `https` when no forwarded-proto header is
 * available. Covers:
 *
 *   - `localhost` (any port)
 *   - the entire `127.0.0.0/8` IPv4 loopback block (RFC 5735)
 *   - `::1` (IPv6 loopback), wrapped in brackets per RFC 7230
 *
 * Anything else -- including `0.0.0.0` (legitimate target for some
 * dev tools but not strictly loopback) and link-local IPv6 -- falls
 * through to the https branch. If a future dev configuration relies
 * on those hosts, set `x-forwarded-proto` explicitly.
 */
function isLoopbackHost(hostHeader: string): boolean {
  let bare = hostHeader;
  if (bare.startsWith("[")) {
    const end = bare.indexOf("]");
    if (end >= 0) bare = bare.slice(1, end);
  } else {
    const colonIdx = bare.lastIndexOf(":");
    if (colonIdx >= 0 && /^\d+$/.test(bare.slice(colonIdx + 1))) {
      bare = bare.slice(0, colonIdx);
    }
  }
  bare = bare.toLowerCase();
  if (bare === "localhost") return true;
  if (bare === "::1") return true;
  return /^127\.\d{1,3}\.\d{1,3}\.\d{1,3}$/.test(bare);
}

/**
 * CSRF defence for state-changing endpoints (`logout`, `refresh`).
 *
 * The session cookie is set with `SameSite=None; Partitioned` so it
 * can flow into the iframe-partitioned dev preview. That attribute
 * means browsers WILL include the cookie on cross-site requests --
 * including a hostile `<form method="POST" action=".../logout">`
 * submitted from `evil.com`. A method-only `405` gate stops
 * `<img src>`-style GET attacks but NOT cross-site form POSTs, so
 * the gate is necessary but not sufficient.
 *
 * Layered check, returning `true` only when we can affirmatively
 * confirm the request is same-origin:
 *
 *   1. `Sec-Fetch-Site` (Fetch Metadata, sent by every modern
 *      browser): require `same-origin` or `none`. `none` covers
 *      address-bar / bookmark navigation; `same-site` is rejected
 *      because subdomain-resident content shouldn't be able to hit
 *      auth endpoints.
 *   2. Legacy fallback when Sec-Fetch-Site is absent: require an
 *      `Origin` header that matches the resolved request origin
 *      (computed via the same getOrigin used for postMessage). All
 *      mainstream browsers send Origin on cross-origin POSTs, so
 *      `null Origin + null Sec-Fetch-Site` is treated as a non-
 *      browser caller and rejected -- safer for a session endpoint
 *      than the old "missing means unknown means trust" default.
 *
 * Returns `true` when the request appears same-origin and `false`
 * otherwise. Callers should respond with `403` on `false`.
 */
export function assertSameSiteRequest(req: IncomingMessage): boolean {
  const fetchSite = readHeader(req, "sec-fetch-site");
  if (fetchSite !== null) {
    return fetchSite === "same-origin" || fetchSite === "none";
  }
  const origin = readHeader(req, "origin");
  if (origin === null) return false;
  const expected = getOrigin(req);
  return expected !== null && origin === expected;
}

function readHeader(req: IncomingMessage, name: string): string | null {
  const value = req.headers[name];
  if (Array.isArray(value)) return value[0] ?? null;
  return typeof value === "string" ? value : null;
}
