// @appbuilder-oauth-v4
// AUTO-GENERATED by setup_oauth. Edit with care -- the LLM may regenerate.

import type { IncomingMessage, ServerResponse } from "node:http";

/**
 * Session cookie helpers. Encrypt-then-MAC payload using AES-256-GCM
 * + HMAC-SHA-256. Mirror of `src/lib/oauth/session-cookie.ts` on the
 * platform side -- changes there should be reflected here so the
 * scaffolded sandbox stays in sync with the platform's own helper.
 *
 * Keys are derived from `SESSION_SECRET` via HKDF-SHA-256 (RFC 5869)
 * with a fixed application salt and per-context info labels. Bumping
 * `HKDF_SALT_V1` invalidates all sessions minted under the prior
 * derivation; users get bumped to anonymous and re-sign in (same
 * recovery shape as a SESSION_SECRET rotation).
 */

const COOKIE_NAME = "__appbuilder_session";
const MAX_AGE_SECONDS = 60 * 60 * 24 * 7; // 7 days
const BASE64URL_PADDING = /=+$/g;

function toBase64Url(bytes: Uint8Array): string {
  let binary = "";
  for (let i = 0; i < bytes.length; i++) binary += String.fromCharCode(bytes[i]);
  return btoa(binary).replace(BASE64URL_PADDING, "").replace(/\+/g, "-").replace(/\//g, "_");
}

function fromBase64Url(value: string): Uint8Array<ArrayBuffer> {
  const padded = value.replace(/-/g, "+").replace(/_/g, "/") + "===".slice(0, (4 - (value.length % 4)) % 4);
  const binary = atob(padded);
  const bytes = new Uint8Array(binary.length);
  for (let i = 0; i < binary.length; i++) bytes[i] = binary.charCodeAt(i);
  return bytes;
}

function constantTimeEqual(a: Uint8Array, b: Uint8Array): boolean {
  if (a.length !== b.length) return false;
  let diff = 0;
  for (let i = 0; i < a.length; i++) diff |= a[i] ^ b[i];
  return diff === 0;
}

// Bump the version suffix to invalidate all in-flight sessions if
// the derivation contract ever changes. HKDF doesn't require a
// secret salt; a fixed label is sufficient for domain separation.
const HKDF_SALT_V1 = new TextEncoder().encode("appbuilder-oauth-session-cookie/v1");

async function deriveKey(
  secret: string,
  info: string,
  usage: KeyUsage[],
  algorithm: AesKeyGenParams | HmacImportParams,
): Promise<CryptoKey> {
  const ikm = new TextEncoder().encode(secret);
  const hkdfKey = await crypto.subtle.importKey("raw", ikm, "HKDF", false, ["deriveKey"]);
  return crypto.subtle.deriveKey(
    {
      name: "HKDF",
      hash: "SHA-256",
      salt: HKDF_SALT_V1,
      info: new TextEncoder().encode(info),
    },
    hkdfKey,
    algorithm,
    false,
    usage,
  );
}

async function deriveAesKey(secret: string): Promise<CryptoKey> {
  return deriveKey(secret, "aes-256-gcm", ["encrypt", "decrypt"], { name: "AES-GCM", length: 256 });
}

async function deriveHmacKey(secret: string): Promise<CryptoKey> {
  return deriveKey(secret, "hmac-sha-256", ["sign", "verify"], { name: "HMAC", hash: "SHA-256" });
}

export type SessionPayload = {
  sub: string;
  email?: string;
  name?: string;
  picture?: string;
  provider: string;
  iat: number;
  exp: number;
};

export async function encryptAndSign(payload: unknown, secret: string): Promise<string> {
  if (!secret || secret.length < 16) throw new Error("session secret must be at least 16 characters");
  const aesKey = await deriveAesKey(secret);
  const hmacKey = await deriveHmacKey(secret);
  const iv = new Uint8Array(12);
  crypto.getRandomValues(iv);
  const plaintext = new TextEncoder().encode(JSON.stringify(payload));
  const ciphertextBuf = await crypto.subtle.encrypt({ name: "AES-GCM", iv }, aesKey, plaintext);
  const ciphertext = new Uint8Array(ciphertextBuf);
  const macInput = new Uint8Array(iv.length + ciphertext.length);
  macInput.set(iv, 0);
  macInput.set(ciphertext, iv.length);
  const macBuf = await crypto.subtle.sign({ name: "HMAC" }, hmacKey, macInput);
  const mac = new Uint8Array(macBuf);
  return `${toBase64Url(iv)}.${toBase64Url(ciphertext)}.${toBase64Url(mac)}`;
}

export async function verifyAndDecrypt<T = unknown>(cookie: string, secret: string): Promise<T | null> {
  if (!secret || secret.length < 16) return null;
  if (!cookie) return null;
  const parts = cookie.split(".");
  if (parts.length !== 3) return null;
  let iv: Uint8Array<ArrayBuffer>;
  let ciphertext: Uint8Array<ArrayBuffer>;
  let mac: Uint8Array<ArrayBuffer>;
  try {
    iv = fromBase64Url(parts[0]);
    ciphertext = fromBase64Url(parts[1]);
    mac = fromBase64Url(parts[2]);
  } catch {
    return null;
  }
  if (iv.length !== 12 || mac.length !== 32) return null;
  let aesKey: CryptoKey;
  let hmacKey: CryptoKey;
  try {
    aesKey = await deriveAesKey(secret);
    hmacKey = await deriveHmacKey(secret);
  } catch {
    return null;
  }
  const macInput = new Uint8Array(iv.length + ciphertext.length);
  macInput.set(iv, 0);
  macInput.set(ciphertext, iv.length);
  let expectedMac: Uint8Array;
  try {
    const expectedBuf = await crypto.subtle.sign({ name: "HMAC" }, hmacKey, macInput);
    expectedMac = new Uint8Array(expectedBuf);
  } catch {
    return null;
  }
  if (!constantTimeEqual(mac, expectedMac)) return null;
  let plaintextBuf: ArrayBuffer;
  try {
    plaintextBuf = await crypto.subtle.decrypt({ name: "AES-GCM", iv }, aesKey, ciphertext);
  } catch {
    return null;
  }
  try {
    return JSON.parse(new TextDecoder().decode(plaintextBuf)) as T;
  } catch {
    return null;
  }
}

/**
 * Build a Set-Cookie header for the session.
 *
 * Cookie attributes:
 *   - `SameSite=None; Secure`: required because the AppBuilder
 *     preview iframe is cross-site relative to its parent; the
 *     browser treats the iframe as a third-party context and won't
 *     send Lax cookies inside it.
 *   - `Partitioned` (CHIPS): in browsers with third-party-cookie
 *     blocking enabled (default in Chrome from 2026), unpartitioned
 *     cross-site cookies are not sent regardless of `SameSite`. The
 *     Partitioned attribute opts the cookie into the partition keyed
 *     by the *top-level* site at the time of Set-Cookie. So:
 *       - When the deployed app sets the cookie at top-level
 *         (`actual-deployed-site`), it lands in
 *         `(top=actual-deployed-site)` and is sent on subsequent
 *         requests from that same top-level site -- works.
 *       - When the dev-preview popup callback sets it at top-level
 *         on `sandbox-host`, it lands in `(top=sandbox-host)` -- and
 *         the AppBuilder iframe (`top=AppBuilder`) cannot read it.
 *         The dev preview works around this with the postMessage
 *         exchange flow (`api/auth/exchange.ts`): the iframe
 *         re-issues the session by POSTing a short-lived signed
 *         token, and the exchange endpoint sets the Partitioned
 *         cookie inside the iframe's partition.
 *     Browsers that don't recognise `Partitioned` ignore it and
 *     treat the cookie as unpartitioned; this is exactly the legacy
 *     behaviour, so adding the attribute is strictly additive.
 */
export function buildSessionSetCookie(value: string): string {
  const attrs = [
    `${COOKIE_NAME}=${value}`,
    "Path=/",
    "HttpOnly",
    "Secure",
    "SameSite=None",
    "Partitioned",
    `Max-Age=${MAX_AGE_SECONDS}`,
  ];
  return attrs.join("; ");
}

export function buildSessionClearCookie(): string {
  return `${COOKIE_NAME}=; Path=/; HttpOnly; Secure; SameSite=None; Partitioned; Max-Age=0`;
}

/* ---------------------------------------------------------------- */
/* Exchange tokens for the iframe-partitioned session handoff       */
/* ---------------------------------------------------------------- */

/**
 * Short-lived (60s) HMAC-signed envelope around a session payload,
 * minted by `api/auth/<provider>/callback` and posted to the
 * opener via `window.postMessage`. The iframe redeems the token at
 * `POST /api/auth/exchange` to get a Partitioned session cookie
 * usable inside its own (top=AppBuilder) partition. The exchange
 * endpoint validates the HMAC and then re-emits the session via
 * `setSession`, so an attacker who intercepts the token can only
 * impersonate the user for the 60-second window before it expires.
 *
 * Format: `<base64url(payload)>.<base64url(mac)>` where `payload` is
 * `{ s: SessionPayload, exp: <unix-seconds-deadline> }`.
 */
const EXCHANGE_TOKEN_TTL_SECONDS = 60;

export async function mintExchangeToken(payload: SessionPayload): Promise<string> {
  const secret = process.env.SESSION_SECRET ?? "";
  if (!secret || secret.length < 16) throw new Error("session secret must be at least 16 characters");
  const exp = Math.floor(Date.now() / 1000) + EXCHANGE_TOKEN_TTL_SECONDS;
  const envelope = JSON.stringify({ s: payload, exp });
  const envelopeBytes = new TextEncoder().encode(envelope);
  const hmacKey = await deriveHmacKey(secret);
  const macBuf = await crypto.subtle.sign({ name: "HMAC" }, hmacKey, envelopeBytes);
  return `${toBase64Url(envelopeBytes)}.${toBase64Url(new Uint8Array(macBuf))}`;
}

export async function verifyExchangeToken(token: string): Promise<SessionPayload | null> {
  const secret = process.env.SESSION_SECRET ?? "";
  if (!secret || secret.length < 16) return null;
  if (!token || token.length > 4096) return null; // bound the work for an attacker.
  const dot = token.indexOf(".");
  if (dot <= 0 || dot === token.length - 1) return null;
  let envelopeBytes: Uint8Array<ArrayBuffer>;
  let mac: Uint8Array<ArrayBuffer>;
  try {
    envelopeBytes = fromBase64Url(token.slice(0, dot));
    mac = fromBase64Url(token.slice(dot + 1));
  } catch {
    return null;
  }
  if (mac.length !== 32) return null;
  let expectedMac: Uint8Array;
  try {
    const hmacKey = await deriveHmacKey(secret);
    const macBuf = await crypto.subtle.sign({ name: "HMAC" }, hmacKey, envelopeBytes);
    expectedMac = new Uint8Array(macBuf);
  } catch {
    return null;
  }
  if (!constantTimeEqual(mac, expectedMac)) return null;
  let parsed: { s?: SessionPayload; exp?: number };
  try {
    parsed = JSON.parse(new TextDecoder().decode(envelopeBytes)) as { s?: SessionPayload; exp?: number };
  } catch {
    return null;
  }
  if (!parsed.s || typeof parsed.exp !== "number") return null;
  if (parsed.exp * 1000 < Date.now()) return null;
  return parsed.s;
}

export function readSessionCookie(req: IncomingMessage): string | null {
  const raw = req.headers.cookie;
  if (!raw) return null;
  const parts = raw.split(/;\s*/);
  for (const p of parts) {
    const idx = p.indexOf("=");
    if (idx <= 0) continue;
    const key = p.slice(0, idx).trim();
    if (key === COOKIE_NAME) return decodeURIComponent(p.slice(idx + 1));
  }
  return null;
}

export async function loadSession(req: IncomingMessage): Promise<SessionPayload | null> {
  const secret = process.env.SESSION_SECRET ?? "";
  const cookie = readSessionCookie(req);
  if (!cookie) return null;
  const payload = await verifyAndDecrypt<SessionPayload>(cookie, secret);
  if (!payload) return null;
  if (typeof payload.exp === "number" && payload.exp * 1000 < Date.now()) return null;
  return payload;
}

export async function setSession(res: ServerResponse, payload: SessionPayload): Promise<void> {
  const secret = process.env.SESSION_SECRET ?? "";
  const cookie = await encryptAndSign(payload, secret);
  res.setHeader("Set-Cookie", buildSessionSetCookie(cookie));
}

export function clearSession(res: ServerResponse): void {
  res.setHeader("Set-Cookie", buildSessionClearCookie());
}
