// @appbuilder-oauth-v4
// AUTO-GENERATED by setup_oauth. Edit with care -- the LLM may regenerate.

import type { IncomingMessage, ServerResponse } from "node:http";
// See the rationale on the matching imports in start.ts: `.js`
// extensions are required for Node's strict ESM resolver on Vercel.
import { getProvider } from "../_lib/oauth-providers.js";
import { getOrigin, getRedirectUri } from "../_lib/redirect-uri.js";
import { mintExchangeToken, setSession, type SessionPayload } from "../_lib/session.js";
// Static import so Vercel NFT always bundles the allowlist helper with this function.
import { ensureApprovedForSignIn } from "../../_lib/require-auth.js";

const STATE_COOKIE_PREFIX = "oauth_state_";
const VERIFIER_COOKIE_PREFIX = "oauth_verifier_";
const RETURN_TO_COOKIE_PREFIX = "oauth_return_to_";

/**
 * Complete the OAuth flow: exchange the auth code for tokens, fetch
 * the user profile, set the session cookie, and conclude.
 *
 * Top-level try/catch prevents uncaught throws (e.g. missing
 * SESSION_SECRET inside setSession) from becoming FUNCTION_INVOCATION_FAILED.
 */
export default async function handler(req: IncomingMessage, res: ServerResponse) {
  const targetOrigin = getOrigin(req) ?? "*";
  try {
    return await handleCallback(req, res, targetOrigin);
  } catch (err) {
    const message =
      err instanceof Error ? err.message : "Unexpected error during Google sign-in.";
    return renderError(res, targetOrigin, "callback_crashed", message.slice(0, 500));
  }
}

async function handleCallback(
  req: IncomingMessage,
  res: ServerResponse,
  targetOrigin: string,
) {
  const provider = getProvider("google");
  if (!provider) {
    return renderError(res, targetOrigin, "provider_not_configured", "Provider is not configured.");
  }

  // Fail fast with a readable error instead of throwing inside setSession
  // (missing SESSION_SECRET was causing FUNCTION_INVOCATION_FAILED on Vercel).
  const sessionSecret = (process.env.SESSION_SECRET ?? "").trim();
  if (!sessionSecret || sessionSecret.length < 16) {
    return renderError(
      res,
      targetOrigin,
      "missing_session_secret",
      "SESSION_SECRET is missing or too short in this deployment. " +
        "In Vercel → Project → Settings → Environment Variables, add SESSION_SECRET " +
        "(a random string, 32+ characters), enable Production + Preview, then Redeploy.",
    );
  }

  const url = new URL(`http://x${req.url ?? ""}`); // origin is dummy; we only need search params
  const code = url.searchParams.get("code");
  const stateParam = url.searchParams.get("state");
  const error = url.searchParams.get("error");
  if (error) return renderError(res, targetOrigin, error, url.searchParams.get("error_description") ?? error);
  if (!code || !stateParam) return renderError(res, targetOrigin, "missing_params", "Missing code or state in callback URL.");

  const cookies = parseCookies(req.headers.cookie ?? "");
  const expectedState = cookies[`${STATE_COOKIE_PREFIX}google`];
  const codeVerifier = cookies[`${VERIFIER_COOKIE_PREFIX}google`];
  if (!expectedState || expectedState !== stateParam) {
    return renderError(res, targetOrigin, "state_mismatch", "OAuth state did not match. Restart the sign-in flow.");
  }
  if (!codeVerifier) {
    return renderError(res, targetOrigin, "missing_verifier", "PKCE verifier not found. Restart the sign-in flow.");
  }

  const clientId = process.env[provider.clientIdEnv];
  const clientSecret = process.env[provider.clientSecretEnv];
  if (!clientId || !clientSecret) {
    return renderError(res, targetOrigin, "missing_client_credentials", `Missing ${provider.clientIdEnv} or ${provider.clientSecretEnv}.`);
  }

  const redirectUri = getRedirectUri(req, provider.id);

  const tokenResp = await fetch(provider.tokenUrl, {
    method: "POST",
    headers: { "Content-Type": "application/x-www-form-urlencoded" },
    body: new URLSearchParams({
      grant_type: "authorization_code",
      code,
      client_id: clientId,
      client_secret: clientSecret,
      redirect_uri: redirectUri,
      code_verifier: codeVerifier,
    }).toString(),
  });
  if (!tokenResp.ok) {
    const text = await tokenResp.text();
    return renderError(res, targetOrigin, "token_exchange_failed", text.slice(0, 500));
  }
  const tokens = (await tokenResp.json()) as {
    access_token?: string;
    id_token?: string;
    refresh_token?: string;
    expires_in?: number;
  };

  let profile: { sub?: string; email?: string; name?: string; picture?: string } = {};
  if (provider.userInfoUrl && tokens.access_token) {
    try {
      const profileResp = await fetch(provider.userInfoUrl, {
        headers: { Authorization: `Bearer ${tokens.access_token}` },
      });
      if (profileResp.ok) profile = (await profileResp.json()) as typeof profile;
    } catch {
      // Best-effort; the session will still be created even without profile data.
    }
  }

  if (!profile.sub) {
    return renderError(res, targetOrigin, "missing_subject", "Provider did not return a stable user id.");
  }

  // Only approved Google emails may receive a session cookie.
  // First successful sign-in bootstraps the allowlist as admin when empty.
  try {
    const gate = await ensureApprovedForSignIn({
      email: profile.email,
      name: profile.name,
    });
    if (!gate.ok) {
      return renderError(res, targetOrigin, gate.code, gate.message);
    }
  } catch (err) {
    const message =
      err instanceof Error ? err.message : "Failed to verify approved access list.";
    return renderError(res, targetOrigin, "allowlist_error", message.slice(0, 500));
  }

  const now = Math.floor(Date.now() / 1000);
  const payload: SessionPayload = {
    sub: profile.sub,
    email: profile.email,
    name: profile.name,
    picture: profile.picture,
    provider: provider.id,
    iat: now,
    exp: now + 60 * 60 * 24 * 7,
  };
  try {
    await setSession(res, payload);
  } catch (err) {
    const message =
      err instanceof Error ? err.message : "Failed to create session cookie.";
    return renderError(
      res,
      targetOrigin,
      "session_create_failed",
      `${message}. Ensure SESSION_SECRET is set in Vercel (Production + Preview) and redeploy.`,
    );
  }

  // Mint a short-lived HMAC-signed exchange token so the AppBuilder
  // iframe (which lives in a different cookie partition than this
  // top-level popup) can re-issue the session inside its own
  // partition by POSTing to /api/auth/exchange. See exchange.ts for
  // the full rationale.
  let exchangeToken: string | null = null;
  try {
    exchangeToken = await mintExchangeToken(payload);
  } catch {
    // Best-effort: a missing SESSION_SECRET will throw here. The
    // first-party session cookie is still set, so the deployed app
    // (no iframe) keeps working; only the dev-preview iframe sees a
    // degraded experience until the secret is registered.
    exchangeToken = null;
  }

  // Clear the one-shot PKCE / state cookies. Attributes match the
  // ones set by start.ts (Lax) so cleared cookies don't accidentally
  // get re-resurrected by a stale None copy from a v1 sandbox. The
  // returnTo cookie is cleared on the same pass so it can't survive
  // a successful sign-in and accidentally redirect a future popup-
  // mode flow that thought it was anonymous.
  const expired = (name: string) => `${name}=; Path=/; HttpOnly; Secure; SameSite=Lax; Max-Age=0`;
  res.appendHeader?.("Set-Cookie", expired(`${STATE_COOKIE_PREFIX}google`));
  res.appendHeader?.("Set-Cookie", expired(`${VERIFIER_COOKIE_PREFIX}google`));
  res.appendHeader?.("Set-Cookie", expired(`${RETURN_TO_COOKIE_PREFIX}google`));

  // Branch on the redirect-flow signal. If start.ts persisted a
  // sanitized returnTo cookie, the user got here via a top-level
  // navigation (popup-blocker fallback) -- there's no opener to
  // postMessage and `window.close()` would close their main tab.
  // 302 back to the saved path; the page will re-mount and
  // AuthProvider's mount-time `refresh()` picks up the new
  // session cookie automatically.
  //
  // Re-validate the cookie value with the same sanitizer start.ts
  // used. The cookie is HttpOnly + Lax so a malicious page can't
  // forge it directly, but defence in depth is cheap here: if the
  // value has somehow been tampered with we fall through to the
  // popup HTML (which is harmless) instead of 302'ing somewhere
  // unexpected.
  const rawReturnTo = cookies[`${RETURN_TO_COOKIE_PREFIX}google`];
  const sanitizedReturnTo = rawReturnTo ? sanitizeReturnTo(rawReturnTo) : null;
  if (sanitizedReturnTo !== null) {
    res.statusCode = 302;
    res.setHeader("Location", sanitizedReturnTo);
    res.end();
    return;
  }

  // Inline the exchange token into the postMessage payload as a
  // JSON literal so the popup HTML stays a single `res.end`. The
  // token is HMAC-signed, not encrypted -- it carries the session
  // payload, but only an attacker holding SESSION_SECRET can mint
  // valid ones, and the 60-second TTL bounds replay risk to the
  // window between mint and exchange.
  const tokenLiteral = exchangeToken === null ? "null" : JSON.stringify(exchangeToken);
  // Same-origin postMessage target. `auth-popup.ts` opens the
  // popup via a relative URL, so the popup's origin equals the
  // opener's origin; addressing the message at `targetOrigin`
  // prevents an attacker who navigated the opener mid-flow (e.g.
  // tabnabbing) from receiving the exchange token.
  //
  // Script-context escape: see `renderStartError` for the
  // rationale -- `JSON.stringify` doesn't escape `<`, and even
  // though the URL parser should reject `</script>` in a host,
  // emitting `\u003c` for any `<` keeps the inline-script
  // guarantee self-contained.
  const targetOriginLiteral = JSON.stringify(targetOrigin).replace(/</g, "\\u003c");
  res.statusCode = 200;
  res.setHeader("Content-Type", "text/html; charset=utf-8");
  res.end(`<!doctype html><meta charset="utf-8"><title>Sign-in complete</title>
<body style="font-family:system-ui;padding:2rem;color:#374151">
<p>Sign-in complete. You can close this window.</p>
<script>
  try {
    if (window.opener) {
      window.opener.postMessage({ type: "appbuilder-oauth-success", provider: "google", exchangeToken: ${tokenLiteral} }, ${targetOriginLiteral});
    }
  } catch (e) {}
  setTimeout(function(){ window.close(); }, 100);
</script>
</body>`);
}

/**
 * Same sanitizer used by start.ts. Duplicated here (rather than
 * extracted into _lib/) so the redirect-flow guarantee is
 * self-contained in each handler -- a future refactor that splits
 * these files apart can't accidentally drop the validation.
 */
function sanitizeReturnTo(raw: string | null): string | null {
  if (!raw) return null;
  if (raw.length > 2048) return null;
  if (/^[a-zA-Z][a-zA-Z0-9+.-]*:/.test(raw)) return null;
  if (raw.startsWith("//")) return null;
  if (!raw.startsWith("/")) return null;
  return raw;
}

function parseCookies(header: string): Record<string, string> {
  const out: Record<string, string> = {};
  for (const part of header.split(/;\s*/)) {
    const idx = part.indexOf("=");
    if (idx <= 0) continue;
    const key = part.slice(0, idx).trim();
    out[key] = decodeURIComponent(part.slice(idx + 1));
  }
  return out;
}

function renderError(res: ServerResponse, targetOrigin: string, code: string, message: string) {
  // Same rationale as the success path: address the error metadata
  // at the popup's own origin so a tabnabbed opener can't observe
  // diagnostic strings (and so attacker-controllable origin chooses
  // can't surface as cross-origin DOM events on a hostile page).
  //
  // Script-context escape: see the success branch above for the
  // rationale on the `.replace(/</g, "\u003c")` follow-up.
  const targetOriginLiteral = JSON.stringify(targetOrigin).replace(/</g, "\\u003c");
  res.statusCode = 400;
  res.setHeader("Content-Type", "text/html; charset=utf-8");
  res.end(`<!doctype html><meta charset="utf-8"><title>Sign-in failed</title>
<body style="font-family:system-ui;padding:2rem;color:#374151">
<h2 style="color:#b91c1c">Sign-in failed</h2>
<p><strong>${escapeHtml(code)}</strong></p>
<pre style="background:#f3f4f6;padding:1rem;border-radius:6px;white-space:pre-wrap;word-break:break-word">${escapeHtml(message)}</pre>
<script>
  try {
    if (window.opener) {
      window.opener.postMessage({ type: "appbuilder-oauth-error", code: "${escapeJs(code)}", message: "${escapeJs(message)}" }, ${targetOriginLiteral});
    }
  } catch (e) {}
</script>
</body>`);
}

function escapeHtml(s: string): string {
  return s.replace(/&/g, "&amp;").replace(/</g, "&lt;").replace(/>/g, "&gt;").replace(/"/g, "&quot;");
}

function escapeJs(s: string): string {
  return s.replace(/\\/g, "\\\\").replace(/"/g, '\\"').replace(/\n/g, "\\n");
}
