// @appbuilder-oauth-v4
// AUTO-GENERATED by setup_oauth. Edit with care -- the LLM may regenerate.

import type { IncomingMessage, ServerResponse } from "node:http";
// IMPORTANT: explicit `.js` extensions on the cross-file imports
// below. The scaffold's package.json sets type=module, so once
// Vercel's build (tsc + nft) emits the .js output for these API
// routes, Node's strict ESM resolver runs at request time and
// REQUIRES the extension; an extensionless relative specifier
// produces ERR_MODULE_NOT_FOUND at the first request and the
// function 500s with FUNCTION_INVOCATION_FAILED. Vite tolerates the
// extensionless form in dev because its resolver is bundler-style,
// which is why this regression is invisible until you deploy.
//
// Tooling-wise the .js suffix is the right thing in source too:
// the scaffold's tsconfig.json runs with moduleResolution=bundler
// (or node16/nodenext for the API folder), both of which accept a
// .js specifier on a .ts source file.
import { getProvider } from "../_lib/oauth-providers.js";
import { getOrigin, getRedirectUri } from "../_lib/redirect-uri.js";

const STATE_COOKIE_PREFIX = "oauth_state_";
const VERIFIER_COOKIE_PREFIX = "oauth_verifier_";
const RETURN_TO_COOKIE_PREFIX = "oauth_return_to_";
const COOKIE_TTL_SECONDS = 600; // 10 min: long enough for slow human consent, short enough to bound replay risk.

/**
 * Validate a caller-supplied `returnTo` value. Only same-origin
 * ABSOLUTE PATHS are accepted -- anything that could navigate the
 * user away from this app (scheme, host, protocol-relative `//`)
 * is dropped on the floor and the cookie isn't set, which falls the
 * callback through to the popup HTML branch.
 *
 * This is the "open redirect" guard. Without it, an attacker who
 * could persuade a victim to click a crafted sign-in URL like
 * `/api/auth/google/start?returnTo=https://evil.com` could ride
 * the victim's authenticated session straight into a phishing site.
 * Restricting to absolute paths means the post-callback 302 always
 * lands on the same origin as the API itself.
 */
function sanitizeReturnTo(raw: string | null): string | null {
  if (!raw) return null;
  if (raw.length > 2048) return null; // hard cap to avoid header bloat / cookie size limits
  // Reject any scheme (`http:`, `javascript:`, ...) or
  // protocol-relative URL (`//host/path`). Both would let the
  // attacker pick the post-auth landing origin.
  if (/^[a-zA-Z][a-zA-Z0-9+.-]*:/.test(raw)) return null;
  if (raw.startsWith("//")) return null;
  // Must be an absolute path on this origin. Relative paths and
  // bare query strings are rejected -- handlers can't trust their
  // own URL to anchor a relative path against.
  if (!raw.startsWith("/")) return null;
  return raw;
}

/**
 * Begin the OAuth flow for Google.
 *
 * Invocation contract:
 *   - Method: GET
 *   - The caller is the OAuth popup, navigating directly here at the
 *     **top level** of the user's browser (not via fetch from the
 *     AppBuilder iframe).
 *   - Optional `?scopes=<space-separated>` query param overrides the
 *     provider default.
 *
 * Why a top-level GET instead of the iframe POSTing a "prepare"
 * request and then opening the popup at the provider URL: Chrome's
 * storage partitioning (CHIPS) keys cookies by the top-level frame.
 * If the iframe (top-frame = AppBuilder) wrote the
 * `oauth_state_*` / `oauth_verifier_*` cookies, the popup's
 * top-level callback (top-frame = sandbox host) would read a
 * different cookie jar and the state check would always fail. By
 * letting the popup itself perform the start request, the cookies
 * are written and read in the same first-party partition.
 *
 * Why `SameSite=Lax` (instead of `SameSite=None`): the only
 * cross-site read of these cookies is the provider's 302 redirect
 * back to `/api/auth/<provider>/callback`, which is a top-level
 * GET navigation -- a context where Lax cookies ARE sent. Lax is
 * preferred over None here because these are short-lived single-use
 * cookies that have no business being readable in any other
 * cross-site request.
 *
 * PKCE is generated entirely server-side in this flow. PKCE defends
 * against authorization-code interception in public clients; the
 * scaffold runs as a server-mediated flow (we already trust the
 * server with the client secret), so generating the verifier in the
 * popup-bound start handler and stashing it in an HttpOnly cookie
 * is no weaker than the original "generate in browser, ship in
 * cookie" shape, and removes the need for a preflight POST that
 * doesn't survive cookie partitioning.
 */
export default async function handler(req: IncomingMessage, res: ServerResponse) {
  if (req.method !== "GET") {
    res.statusCode = 405;
    res.setHeader("Allow", "GET");
    res.end("Method Not Allowed");
    return;
  }

  // Resolve the popup's own origin for the postMessage target.
  // Same rationale as in callback.ts: `auth-popup.ts` opens this
  // start URL via a relative path, so the popup's origin equals
  // the opener's, and we want errors addressed there rather than
  // at `"*"`. Falls back to `"*"` only if no host can be
  // resolved (no Host header, exotic proxy chain).
  const targetOrigin = getOrigin(req) ?? "*";

  const provider = getProvider("google");
  if (!provider) {
    return renderStartError(res, targetOrigin, "provider_not_configured", "Provider is not configured.");
  }

  const clientId = process.env[provider.clientIdEnv];
  if (!clientId) {
    return renderStartError(res, targetOrigin, "missing_client_id", `Missing ${provider.clientIdEnv} in environment.`);
  }

  const reqUrl = new URL(`http://x${req.url ?? ""}`); // origin is dummy; we only need search params
  const scopesParam = reqUrl.searchParams.get("scopes");
  const scopes = scopesParam && scopesParam.length > 0 ? scopesParam : provider.defaultScopes;
  // `returnTo` opts into the redirect-flow callback: when present
  // (and same-origin), the callback handler 302s back here instead
  // of rendering the postMessage HTML. Used by auth-popup.ts as the
  // popup-blocker fallback. Absent in the normal popup flow, so the
  // existing postMessage path stays the default.
  const returnTo = sanitizeReturnTo(reqUrl.searchParams.get("returnTo"));

  const codeVerifier = generateBase64UrlBytes(32);
  const codeChallenge = await sha256Base64Url(codeVerifier);
  const state = generateBase64UrlBytes(16);
  const redirectUri = getRedirectUri(req, provider.id);

  const authorizeUrl = new URL(provider.authorizeUrl);
  authorizeUrl.searchParams.set("client_id", clientId);
  authorizeUrl.searchParams.set("redirect_uri", redirectUri);
  authorizeUrl.searchParams.set("response_type", "code");
  authorizeUrl.searchParams.set("scope", scopes);
  authorizeUrl.searchParams.set("state", state);
  authorizeUrl.searchParams.set("code_challenge", codeChallenge);
  authorizeUrl.searchParams.set("code_challenge_method", "S256");
  authorizeUrl.searchParams.set("access_type", "offline");
  authorizeUrl.searchParams.set("prompt", "consent");

  // Build cookies dynamically so the redirect-flow cookie is only
  // emitted when returnTo passed sanitization. Including it
  // unconditionally would mean every popup-mode invocation
  // accidentally landed in redirect mode at callback time.
  const cookies = [
    `${STATE_COOKIE_PREFIX}google=${state}; Path=/; HttpOnly; Secure; SameSite=Lax; Max-Age=${COOKIE_TTL_SECONDS}`,
    `${VERIFIER_COOKIE_PREFIX}google=${codeVerifier}; Path=/; HttpOnly; Secure; SameSite=Lax; Max-Age=${COOKIE_TTL_SECONDS}`,
  ];
  if (returnTo !== null) {
    // URL-encode the path so cookie parsers (which split on `;`)
    // don't choke on a path containing a literal semicolon. The
    // callback decodeURIComponent's it back before redirecting.
    cookies.push(
      `${RETURN_TO_COOKIE_PREFIX}google=${encodeURIComponent(returnTo)}; Path=/; HttpOnly; Secure; SameSite=Lax; Max-Age=${COOKIE_TTL_SECONDS}`,
    );
  }
  res.setHeader("Set-Cookie", cookies);
  res.statusCode = 302;
  res.setHeader("Location", authorizeUrl.toString());
  res.end();
}

function generateBase64UrlBytes(byteLength: number): string {
  const bytes = new Uint8Array(byteLength);
  crypto.getRandomValues(bytes);
  let binary = "";
  for (let i = 0; i < bytes.length; i++) binary += String.fromCharCode(bytes[i]);
  return btoa(binary).replace(/=+$/g, "").replace(/\+/g, "-").replace(/\//g, "_");
}

async function sha256Base64Url(input: string): Promise<string> {
  const data = new TextEncoder().encode(input);
  const digest = await crypto.subtle.digest("SHA-256", data);
  const bytes = new Uint8Array(digest);
  let binary = "";
  for (let i = 0; i < bytes.length; i++) binary += String.fromCharCode(bytes[i]);
  return btoa(binary).replace(/=+$/g, "").replace(/\+/g, "-").replace(/\//g, "_");
}

/**
 * Render a configuration error inline so the popup user sees what
 * went wrong instead of a blank tab. Posts a structured error back
 * to the opener (matching the callback's error shape) so the React
 * app can surface it via the standard message handler.
 */
function renderStartError(res: ServerResponse, targetOrigin: string, code: string, message: string) {
  // Same rationale as the callback's renderError: address the
  // error metadata at the popup's own origin so a tabnabbed
  // opener can't observe diagnostic strings.
  //
  // Defensive script-context escape: `JSON.stringify` does not
  // escape `<`, so a header-derived targetOrigin containing a
  // `</script>` sequence could break out of the inline script
  // tag. The URL parser should reject such hosts in the first
  // place (`<` and `>` are not valid host chars), but emitting
  // `\u003c` for any `<` keeps the script-context guarantee
  // self-contained -- if a future refactor of `getOrigin` ever
  // returns something unsanitised, the script tag still holds.
  const targetOriginLiteral = JSON.stringify(targetOrigin).replace(/</g, "\\u003c");
  res.statusCode = 400;
  res.setHeader("Content-Type", "text/html; charset=utf-8");
  res.end(`<!doctype html><meta charset="utf-8"><title>Sign-in failed</title>
<body style="font-family:system-ui;padding:2rem;color:#374151">
<h2 style="color:#b91c1c">Sign-in failed</h2>
<p><strong>${escapeHtml(code)}</strong></p>
<pre style="background:#f3f4f6;padding:1rem;border-radius:6px;white-space:pre-wrap;word-break:break-word">${escapeHtml(message)}</pre>
<script>
  try {
    if (window.opener) {
      window.opener.postMessage({ type: "appbuilder-oauth-error", code: "${escapeJs(code)}", message: "${escapeJs(message)}" }, ${targetOriginLiteral});
    }
  } catch (e) {}
</script>
</body>`);
}

function escapeHtml(s: string): string {
  return s.replace(/&/g, "&amp;").replace(/</g, "&lt;").replace(/>/g, "&gt;").replace(/"/g, "&quot;");
}

function escapeJs(s: string): string {
  return s.replace(/\\/g, "\\\\").replace(/"/g, '\\"').replace(/\n/g, "\\n");
}
